// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvagxwvkjveqqxbymrxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2YWd4d3ZranZlcXF4YnltcnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzQyOTQsImV4cCI6MjA2MDUxMDI5NH0.kbqjRNHwVvOyHevxYEDgIwwmBXrgjn2PIWfRyQuFUNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);